name: Python script

on: [push]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run script
      env:
          AZURE_SECRET_TOKEN: ${{ secrets.AZURE_SECRET_TOKEN }}
      run: python main.py
